### ISSUE TITLE
The link to pretrained model and dataset seem to not working

### ISSUE THREAD

**Issue by petpetpeter** [aseuteurideu/LearningNotToReconstructAnomalies#1]
Hi, thank you for your effort in sharing this amazing repo.

I would like to try following the sample but the link to download the pre-trained weight is not working.

[https://drive.google.com/file/d/1jE4Y4PKZn6NswjMEnAk_cKvxsRofJ_xT/view?usp=sharing](https://drive.google.com/file/d/1jE4Y4PKZn6NswjMEnAk_cKvxsRofJ_xT/view?usp=sharing)

Could you provide a new URL to download it?

Thank you in advance.

**Comment by aseuteurideu** [comment]
Thank you for your notification. I have updated the links in the README files.

**Comment by aseuteurideu** [comment]
Due to sudden problem with my google drive. The files again can't be accessed again. I'll give you update after I have place to upload my weight files.

**Comment by petpetpeter** [comment]
Thank you for your very fast response,
Looking forward to it.

**Comment by aseuteurideu** [comment]
I have updated the link.
