### ISSUE TITLE
Training Epochs

### ISSUE THREAD

**Issue by rayush7** [aseuteurideu/LearningNotToReconstructAnomalies#2]
Hi @aseuteurideu 

Could you please let me know for how many epochs did you train the autoencoder with patch-based and skip-frame based pseudo-anomalies for? I cannot find this information in the paper https://arxiv.org/pdf/2110.09742.pdf.

Please help.

**Comment by aseuteurideu** [comment]
It's the default value of the code: 60 epochs. But we checked the performance in each epoch and select the best one
