### ISSUE TITLE
How to choose the best model to evaluate?

### ISSUE THREAD

**Issue by JPerAsperaadAstra** [aseuteurideu/LearningNotToReconstructAnomalies#3]

**Comment by JPerAsperaadAstra** [comment]
Hi dear author, I'm wondering based on what metrics should I choose the best .pth trained models to evaluate. Since I found that using the .pth with lowest mean reconstruction loss (e.g. for baseline method) do not necessarily gives the best evaluation results. So I wonder how you choose the .pth to evaluate on.

**Comment by aseuteurideu** [comment]
I evaluated all .pth and selected the best AUC.
(Yeah, validating on test data is not the ideal approach indeed. But both the baseline and the approach got the same treatment)
